post_install() {
  systemctl daemon-reload >/dev/null 2>&1 || true
  systemctl enable soft-connect-desk.service >/dev/null 2>&1 || true
  update-desktop-database >/dev/null 2>&1 || true
}

post_upgrade() {
  post_install
}

pre_remove() {
  systemctl stop soft-connect-desk.service >/dev/null 2>&1 || true
  systemctl disable soft-connect-desk.service >/dev/null 2>&1 || true
}

post_remove() {
  systemctl daemon-reload >/dev/null 2>&1 || true
  update-desktop-database >/dev/null 2>&1 || true
}
