#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/soft-connect-desk/soft-connect-desk /usr/bin/soft-connect-desk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/soft-connect-desk.service ]; then
			rm /etc/systemd/system/soft-connect-desk.service /usr/lib/systemd/system/soft-connect-desk.service /usr/lib/systemd/user/soft-connect-desk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/soft-connect-desk/files/systemd/soft-connect-desk.service /usr/lib/systemd/system/soft-connect-desk.service
		# try fix error in Ubuntu 18.04
		# Ensure pkill uses an absolute path on older distributions.
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/soft-connect-desk.service
		fi
		systemctl daemon-reload
		systemctl enable soft-connect-desk
		systemctl start soft-connect-desk
	fi
fi
